// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TourPortal.Data;

#nullable disable

namespace TourPortal.Migrations
{
    [DbContext(typeof(TravelPortalContext))]
    partial class TravelPortalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TourPortal.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("TourPortal.Models.Gallery", b =>
                {
                    b.Property<int>("galleryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("galleryId"));

                    b.Property<string>("galleryImage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("galleryId");

                    b.ToTable("Gallerys");
                });

            modelBuilder.Entity("TourPortal.Models.GalleryBlob", b =>
                {
                    b.Property<int>("galId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("galId"));

                    b.Property<string>("galImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("galName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("galId");

                    b.ToTable("GalleryBlobs");
                });
#pragma warning restore 612, 618
        }
    }
}
